 name: CI
 on: [push]
 jobs:
   run-ci-tests:
     runs-on: ubuntu-latest
     steps:
       - name: checkout repo
         uses: actions/checkout@v2
       - name: Spin up containers
         run: make build
       - name: Run CI test
         run: make ci